name: flutter_playground

workspace:
  - app/
  - core/common/
  - core/designsystem/
  - core/ui/
  - core/locale/
  - core/data/
  - core/domain/
  - core/navigation/
  - model/apiresponse/
  - model/entity/
  - tooling/secreat_env/
  - tooling/code_analyzer/

environment:
  sdk: ^3.10.4

dev_dependencies:
  melos: ^7.1.0

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.10.4

      dependencies:
        common: ^0.0.1
        data: ^0.0.1
        domain: ^0.0.1

        cupertino_icons: ^1.0.8
        logger: ^2.6.1

      dev_dependencies:
        flutter_test:
          sdk: flutter
        flutter_lints: ^6.0.0
        melos: ^6.3.3

  scripts:
    clean_and_get:
      run: melos exec -- flutter clean && melos bootstrap
      description: Cleans and then fetches dependencies for all packages.

    # Production APK builds
    build:apk:production:release:
      run: melos exec --scope="app" -- flutter build apk --target=lib/application/main_production.dart --flavor production --release
      description: Build production APK (release mode)

    # Development APK builds
    build:apk:development:release:
      run: melos exec --scope="app" -- flutter build apk --target=lib/application/main_development.dart --flavor development --release
      description: Build development APK (release mode)

    generate:barrels:
      run: dart run melos_scripts/barrel_generator.dart
      description: Update all package barrel files

    env_secret_generate:
      run: melos exec --scope secret_env -- dart run build_runner build

    update_overrides:
      run: melos exec -- dart run $(pwd)/scripts/pubspec_overrides.dart && melos bootstrap

    update_minor_deps:
      description: Update minor dependencies
      run: dart run scripts/update_melos_minor_deps.dart

    update_major_deps:
      description: Update major dependencies
      run: dart run scripts/update_melos_major_deps.dart
