name: flutter_playground

workspace:
  - app/
  - core/common/
  - core/data/
  - core/domain/
  - model/apiresponse/
  - model/entity/

environment:
  sdk: ^3.10.4

dev_dependencies:
  melos: ^7.1.0

melos:
  command:
    bootstrap:
      environment:
        sdk: ^3.10.4

      dependencies:
        common: ^0.0.1
        data: ^0.0.1
        domain: ^0.0.1

        cupertino_icons: ^1.0.8
        logger: ^2.6.1

      dev_dependencies:
        flutter_test:
          sdk: flutter
        flutter_lints: ^6.0.0
        melos: ^6.3.3

  scripts:
    clean_and_get:
      run: melos exec -- flutter clean && melos bootstrap
      description: Cleans and then fetches dependencies for all packages.

    generate:barrels:
      run: dart run melos_scripts/barrel_generator.dart
      description: Update all package barrel files
