name: app
description: ""
publish_to: "none"
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  code_analyzer: ^0.0.1
  common: ^0.0.1
  domain: ^0.0.1
  data: ^0.0.1
  designsystem: ^0.0.1
  navigation: ^0.0.1
  app_locale: ^1.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  config:
    enable-lldb-debugging: false
